INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(05,'ANTIOQUIA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(08,'ATLANTICO');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(11,'BOGOTA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(13,'BOLIVAR');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(15,'BOYACA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(17,'CALDAS');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(18,'CAQUETA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(19,'CAUCA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(20,'CESAR');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(23,'CORDOBA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(25,'CUNDINAMARCA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(27,'CHOCO');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(41,'HUILA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(44,'LA GUAJIRA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(47,'MAGDALENA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(50,'META');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(52,'NARIÑO');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(54,'N. DE SANTANDER');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(63,'QUINDIO');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(66,'RISARALDA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(68,'SANTANDER');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(70,'SUCRE');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(73,'TOLIMA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(76,'VALLE DEL CAUCA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(81,'ARAUCA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(85,'CASANARE');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(86,'PUTUMAYO');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(88,'SAN ANDRES');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(91,'AMAZONAS');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(94,'GUAINIA');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(95,'GUAVIARE');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(97,'VAUPES');
INSERT INTO tb_departamentos (id_departamento, nombre) VALUES(99,'VICHADA');
